; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Jun 27 2021 17:05:17 GMT+0200 (Central European Summer Time)

