; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu Jul 01 2021 20:15:46 GMT+0200 (Central European Summer Time)

