; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Jun 27 2021 17:05:17 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

