; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu Jul 01 2021 20:15:46 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

